### ISSUE TITLE
Extract only json for SSR ?

### ISSUE THREAD

**Issue by revskill10** [overlookmotel/react-lazy-data#22]
Is there a method to get only JSON instead of `extractor.script()` , like `extractor.getJSON()`.

It could be helpful in case we want a JSON api for out website.

**Comment by overlookmotel** [comment]
You probably figured this out, hence why you closed the issue, but this would do it:

```js
JSON.stringify( extractor.getData() )
```

**Comment by overlookmotel** [comment]
PS @revskill10 How are you finding using this package? I'd be interested in any feedback.

**Comment by revskill10** [comment]
@overlookmotel  Yes, i see `extractor.getData()` in the docs :). Not related, but do you any ETA to support React 6.10+ ? 

Thanks for great library.

**Comment by overlookmotel** [comment]
Actually, that's pretty tricky due to some changes React made in 16.10, which completely break rehydration of `Suspense` on client side. It's a shame they did that, but they keep saying "server-side rendering of Suspense is not supported".

So getting it working again on 16.10 will require some weird workarounds. I do intend to look into it, hopefully in next month. But as there are no major changes to React after 16.9, I've just been sticking to 16.9.

However... for now I think you can get it working with newer React versions by using `.render()` rather than `.hydrate()` on client. That'd be less efficient, but might well work. If you try it, please let me know.
