### ISSUE TITLE
IS_NODE returning false because I'm using JSDOM 

### ISSUE THREAD

**Issue by laggingreflex** [overlookmotel/react-lazy-data#28]
I'm using JSDOM and have a global window object (in node). [This uses][1]:

```js
IS_NODE = typeof window === 'undefined'
```

which causes trouble for me. It might be better to use something like:

```js
IS_NODE = typeof process !== 'undefined' && !process.browser;
```

I'm not sure if using JSDOM the way I'm using (global window) is the best way to go, but I have a lot of frontend things that end up requiring some browser-related thing (window/document/location/locationStorage/etc) or the other, so I thought having them all put in global scope would be a good way to deal with them all at once. 

[1]: https://github.com/overlookmotel/react-lazy-data/blob/e3831855f77b8318959350d5da84683b7734a8c0/src/client/createResourceFactory.js#L17

**Comment by overlookmotel** [comment]
Hi @laggingreflex.

I'm not sure testing for `process` is the way to go. You'll notice the tests failed on your PR #29, because the tests use JSDOM to emulate the browser environment and they want the package to behave exactly like that - as if it's in the browser.

I'm not sure why JSDOM is required for your use case. If packages are built for server-side rendering, they should handle the lack of `window` etc. If they're not, they probably won't work in other ways on server-side.

Can you give me an example of a package which needs `window` on the server side?

I plan at some point to use the `browser` field in `package.json` to provide different builds for server-side and client-side, which would solve this problem. But no time to work on that for now.

If you want this implemented in short term, I'd accept a PR to produce `node.js` and `browser.js` entry points which set the usage explicitly, alongside `index.js` which does auto-detection via existence of `window`. Then in your case, you could import  `react-lazy-data/node` to get the behaviour you want.

If you'd like to do that, shout if you need help.

**Comment by overlookmotel** [comment]
Please see also #16.

**Comment by laggingreflex** [comment]
I was using JSDOM to simply "stub" these things like a global window/location/localStorage that a number of my packages use so they'd at least not give any errors and carry on with rendering. 

But yeah, you're right. I should probably look into packages that can work on server to begin with. 

Your solution sounds perfect. I've solved my issue for now but will see if I really need it and opne a PR. 

Thanks. And great library!
